version: '3'

services:
  app:
    image: test-next-js
    build: .
    ports:
      - 9000:3000
    volumes:
      - ./pages:/app/pages
      - ./public:/app/public
      - ./styles:/app/styles
      - ./components:/app/components
      - ./assets:/app/assets
   
    restart: always
